### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by YujiaHu0819** [alasdairtran/transform-and-tell#40]
Hello Alasdair,

When I try to reproduce the test, I get the following error.
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 1.96 GiB total capacity; 1.09 GiB already allocated; 9.00 MiB free; 1.12 GiB reserved in total by PyTorch)

And I have tried to adjusted the number of the batch size in the config.yaml, but it did not work.
Have you ever encountered this situation? Or do you have any advice for this?

Thank you in advance!

**Comment by alasdairtran** [comment]
Hi Yujia,

What GPU do you have? From the error, it looks like your GPU only has 2GB of memory. Most of my models, for example, were trained on a Titan V with 12GB of memory. 

If reducing the batch size to 1 still gives you OOM error, then you might want to make the model smaller (e.g. reduce the number of layers, hidden size), but then the performance might also suffer.

**Comment by YujiaHu0819** [comment]
Hello again,
Thanks for your quick reply.
It seems to have solved the GPU problem. But there is still an assertion error somewhere.

> Traceback (most recent call last):
>   File "/Users/yujiahu/opt/anaconda3/envs/tell/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/yujiahu/opt/anaconda3/envs/tell/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/yujiahu/Documents/notebook/transform-and-tell-master1/tell/commands/__main__.py", line 103, in <module>
>     main()
>   File "/Users/yujiahu/Documents/notebook/transform-and-tell-master1/tell/commands/__main__.py", line 99, in main
>     args['overrides'], args['eval_suffix'])
>   File "/Users/yujiahu/Documents/notebook/transform-and-tell-master1/tell/commands/evaluate.py", line 74, in evaluate_from_file
>     device, serialization_dir, eval_suffix, batch_weight_key='')
>   File "/Users/yujiahu/Documents/notebook/transform-and-tell-master1/tell/commands/evaluate.py", line 99, in evaluate
>     serialization_dir, f'generations{eval_suffix}.jsonl'))
> AssertionError

Do you have any advices for this?
Thanks a lot!!

**Comment by alasdairtran** [comment]
Yeah if you trace that error (line 99 in `evaluate.py`), you'll see that we raise an error if `generations.jsonl` already exists. So you first need to remove that file inside the `serialization` directory, e.g.

```
rm expt/nytimes/9_transformer_objects/serialization/generations.jsonl
```

or whichever experiment you'd like to run. The `evaluate` script will create `generations.jsonl` again and put the generated captions in there.
